name: Test

on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Установка shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.2' 
      - name: Composer install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Generate coverage report
        run: make test-coverage
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{ github.workspace }}/build/logs/clover.xml:clover
          debug: true
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage/html